
package com.auth.example;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "authenticateService", targetNamespace = "http://example.auth.com/", wsdlLocation = "file:/C:/Users/Usuario/Documents/algo/ServAuth.wsdl")
public class AuthenticateService
    extends Service
{

    private final static URL AUTHENTICATESERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTHENTICATESERVICE_EXCEPTION;
    private final static QName AUTHENTICATESERVICE_QNAME = new QName("http://example.auth.com/", "authenticateService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Usuario/Documents/algo/ServAuth.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTHENTICATESERVICE_WSDL_LOCATION = url;
        AUTHENTICATESERVICE_EXCEPTION = e;
    }

    public AuthenticateService() {
        super(__getWsdlLocation(), AUTHENTICATESERVICE_QNAME);
    }

    public AuthenticateService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTHENTICATESERVICE_QNAME, features);
    }

    public AuthenticateService(URL wsdlLocation) {
        super(wsdlLocation, AUTHENTICATESERVICE_QNAME);
    }

    public AuthenticateService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTHENTICATESERVICE_QNAME, features);
    }

    public AuthenticateService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthenticateService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GenericAuthService
     */
    @WebEndpoint(name = "GenericAuthServicePort")
    public GenericAuthService getGenericAuthServicePort() {
        return super.getPort(new QName("http://example.auth.com/", "GenericAuthServicePort"), GenericAuthService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GenericAuthService
     */
    @WebEndpoint(name = "GenericAuthServicePort")
    public GenericAuthService getGenericAuthServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.auth.com/", "GenericAuthServicePort"), GenericAuthService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTHENTICATESERVICE_EXCEPTION!= null) {
            throw AUTHENTICATESERVICE_EXCEPTION;
        }
        return AUTHENTICATESERVICE_WSDL_LOCATION;
    }

}
