
package com.auth.example;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GenericAuthService", targetNamespace = "http://example.auth.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GenericAuthService {


    /**
     * 
     * @param password
     * @param idUsuario
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authenticateUser", targetNamespace = "http://example.auth.com/", className = "com.auth.example.AuthenticateUser")
    @ResponseWrapper(localName = "authenticateUserResponse", targetNamespace = "http://example.auth.com/", className = "com.auth.example.AuthenticateUserResponse")
    @Action(input = "http://example.auth.com/GenericAuthService/authenticateUserRequest", output = "http://example.auth.com/GenericAuthService/authenticateUserResponse")
    public boolean authenticateUser(
        @WebParam(name = "idUsuario", targetNamespace = "")
        Integer idUsuario,
        @WebParam(name = "password", targetNamespace = "")
        String password);

}
